---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lynq-mysql-secret
  namespace: lynq-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lynq-mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: lynq-mysql
        property: root-password
    - secretKey: mysql-password
      remoteRef:
        key: lynq-mysql
        property: password
