---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lynq
  namespace: monitoring
spec:
  chart:
    spec:
      chart: lynq
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: lynq
  interval: 1h
  values:
    namespace:
      create: true
      name: lynq-system

    dashboard:
      enabled: true

    replicaCount: 1

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: false

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: lynq-dashboard
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/command
                value: ["/app/bff-server"]
              - op: remove
                path: /spec/template/metadata/labels/control-plane
          - target:
              kind: ClusterRole
              name: lynq-dashboard
            patch: |
              - op: replace
                path: /rules/0/apiGroups/0
                value: operator.lynq.sh
