---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weather-scraper
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/default/weather-scraper/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  targetNamespace: default
  dependsOn:
    - name: open-meteo
      namespace: flux-system
