---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./postgres-cluster.yaml
  - ./postgres-externalsecret.yaml
  - ./app-externalsecret.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
