---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jetkvm-cloud-api
  namespace: default
  labels:
    app.kubernetes.io/name: jetkvm-cloud-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jetkvm-cloud-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
