---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-cadvisor
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/monitoring/kubelet-cadvisor/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  targetNamespace: monitoring
  dependsOn:
    - name: victoria-metrics-operator
