---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: consul-sync-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: consul-sync-secret
    creationPolicy: Owner
  data:
    - secretKey: CONSUL_TOKEN
      remoteRef:
        key: consul-acl-token
        property: password
