---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./externalsecret.yaml
  - ./rbac.yaml
  - ./routes/homeassistant.yaml
  - ./routes/plex.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
