---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consul-sync
  labels:
    app.kubernetes.io/name: consul-sync
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: consul-sync
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
