---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zone-editor
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zone-editor
    template:
      engineVersion: v2
      data:
        HA_TOKEN: "{{ .haToken }}"
  data:
    - secretKey: haToken
      remoteRef:
        key: zone-editor
        property: ha_token
