---
apiVersion: v1
kind: Service
metadata:
  name: zone-editor
  namespace: default
  labels:
    app.kubernetes.io/name: zone-editor
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8099
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: zone-editor
