---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./node-exporter/ks.yaml
  - ./victoria-metrics/ks.yaml
  - ./victoria-logs/ks.yaml
  - ./grafana/ks.yaml
