apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:6XsQ1y9ApJ6pmlKWPTo6HGeSPiNU//9KOfF/foqaOd1mcdIYD8vUyioqcmr3mk8FJd5Pp7O8GtCk+iv9JVA32vY/x3x0xZxR8ab5vWiNI9wiSzlW793jhqCOEE60RHADtu7JI985KPJrpQ62Zj5ihOJmyHnwEfGydRsfNrzP8PGyYiXLq5dfvgCfJQrZ06kPJ8kIKnP/CHUbpyX2csQ/LWy3WvgjRpUEJb6QizlEquAMkRnKyv6SuGcDw5Ilr7AUN+aAP9DoUmfS7bNIiLPO0F/UbVv7KOCwiQyKPT/PEn/0zTAr+0pDb/X4JfZqY6a9gWdkYr8TeZiOXtUiu08cK2QKcSenvKK1L+it+SG+WTrv/rmGQ1EOtdC3J1jbXVOQxoVBurwZ9zJO0PA4wsNiDYkXV0GdS4madEJF8FPVv7sBlCh+LP3PBI7WrfwqFGsbINALG5O13vjgZGOicjZtGl0VVDVNPdcTQmrbz1oWxMcIAFWV09TQb1TuKEvzH9B5Q3QAUgl+T579T+Ro13i+8mGuBoij/hMJitDaHi8Dk+iCDYsmbSaUllHtecUPZ7xvI0SWddBQs3Ey1RMEmCOktTWA+3BR2Cd1kDM5UVjKvqf9MmSPWs6rFuwkpKlVN5+GyffTWtTMqMgasSYweYdVFc+qLEbqgKkbg8i0c7IoucJkTSzazSy/icjS7UF8svIShwGIAwxMRtbFUIrhuw4JPfe/pllrvq21QWugzhTnCH1ubwga9q+OPQNNQOx02HmwMmgt6FWpjrTDEhVsfj8qo7jLtM9qvxvz13yoARn4N//QUwlMcOgwKQxWt2fAgutue+kaUJowMqC18MOWZFGixS2aUPFP41qEnoo2wtUu+JTj9T/029Yp/76sUHx7FVAdkgaH7L3j3D8qKVDZF1YTNL35NF3Fg0PExO0nj5Ge2C9hsvzKtVKC0grEy93Wxxtwcabq4WuqLByYPuiEemoGS5RjXHCyL2gKL18SP9uzEYWrh3WeUJNQW3nSN3Qsz+MIwowieoqGAJdBu+M6KFUpzPhB9WCL13UPnVDsdXNWeyy+RE8D4JZGxixbZTsMCa6aWZpES5R0buMsOkfYlH2QQuM3mrssAZSIXVNet1rxsnVAOY+/rmToPnODSvA=,iv:bc3QwHvDtTCAwM4AaHcqpP2ByvOyzIkX/S4a9P59Lv8=,tag:/G9ux+AfuYfzFABlICks6A==,type:str]
sops:
  age:
    - recipient: age130g6zdklea9zw6n4ddm7ffn4dewvyexjps0q9zfse2df72umqazslr0lc3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWklQMS9KRGN3NTY3SE84
        VDI0bWJVbWplcWkyQzJyMWNvUnFTaWVRbzFnCnhtYThQOWhoSk52VnZVWXpjbEt0
        Wi90dFo0enFiaTh2WEZGeWhpREcxOXMKLS0tIHNhaTAybituYXRkVlZTUDJla1cv
        S0ovZUF4U1NkN0VzK1VobHhBcjlwaEkKPcDBT7OffUqkJDd1csPb5TEKNPTaWwRN
        j2291ybNl2HCTK9lz1Y871CY3RiL+N28QOCGKNOR1mS0+26QwZKJkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T18:12:44Z"
  mac: ENC[AES256_GCM,data:Tei4UF+55782cm/peSPQREcXn3fbbhIHmOC6qtAu8JdCqUkxAYUHkhLNgcONIU7vlwbXOUW8JjAMZTuvp8fGGBKSj0g0La3BG5fz04TUJVP86sC1/d84XH/FHUl2ZMAnJQzjW3tYta8+6+M4dqxv3NofIAetcU8XzEavDQLa5hk=,iv:+2KUN7WHssCImLO9LfxXIVm0GAT1pfsCv0mH7dtwQyc=,tag:rdeooe1yscIsuAk0GpDt4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
