---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-dns-internal
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/network/cloudflare-dns-internal/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  dependsOn:
    - name: cloudflare-dns
  targetNamespace: network
