---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-metrics-operator
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: victoria-metrics-operator
      app.kubernetes.io/name: victoria-metrics-operator
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
