---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: arc-runner-set
  namespace: flux-system
spec:
  targetNamespace: arc-runners
  commonMetadata:
    labels:
      app.kubernetes.io/name: arc-runner-set
  dependsOn:
    - name: arc-controller
  path: ./kubernetes/apps/arc-runners/arc-runner-set/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
