---
apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux
    app.kubernetes.io/component: source-controller
spec:
  type: ClusterIP
  ports:
    - name: http-prom
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: source-controller
---
apiVersion: v1
kind: Service
metadata:
  name: kustomize-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux
    app.kubernetes.io/component: kustomize-controller
spec:
  type: ClusterIP
  ports:
    - name: http-prom
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kustomize-controller
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux
    app.kubernetes.io/component: helm-controller
spec:
  type: ClusterIP
  ports:
    - name: http-prom
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: helm-controller
---
apiVersion: v1
kind: Service
metadata:
  name: notification-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux
    app.kubernetes.io/component: notification-controller
spec:
  type: ClusterIP
  ports:
    - name: http-prom
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: notification-controller
