---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: arc-github-app-secret
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: arc-github-app
        property: app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: arc-github-app
        property: installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: arc-github-app
        property: notesPlain  # Uses the "notes" field which preserves newlines

