---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: falcosidekick-ui-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: falcosidekick-ui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Falcosidekick UI expects credentials in "user:password" format
        FALCOSIDEKICK_UI_USER: "{{ .username }}:{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: falcosidekick-ui
        property: username
    - secretKey: password
      remoteRef:
        key: falcosidekick-ui
        property: password
