---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: consul-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: consul-secret
    creationPolicy: Owner
    template:
      data:
        acl.json: |
          {
            "acl": {
              "enabled": true,
              "default_policy": "deny",
              "tokens": {
                "initial_management": "{{ .CONSUL_BOOTSTRAP_TOKEN }}"
              }
            }
          }
  data:
    - secretKey: CONSUL_BOOTSTRAP_TOKEN
      remoteRef:
        key: consul-acl-token
        property: credential
