---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./httproute.yaml
  - ./httproute-external.yaml
  - ./securitypolicy.yaml
  - ./externalsecret.yaml
