---
# Patch to remove default annotation from local-path storage class
# This allows Longhorn to become the default storage class
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-patch
  namespace: longhorn-system
data:
  patch.yaml: |
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: local-path
      annotations:
        storageclass.kubernetes.io/is-default-class: "false"
