---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: librechat
  namespace: default
  labels:
    app.kubernetes.io/name: librechat
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: librechat
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: librechat-mongodb
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/instance: librechat
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
