---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: victoria-metrics-write
  namespace: monitoring
spec:
  hostnames: ["vlogs-write.k8s.alexieff.io"]
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: victoria-logs-victoria-logs-single-server
          port: 9428
