---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./cloudflare-dns/ks.yaml
  - ./cloudflare-dns-internal/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./consul/ks.yaml
  #- ./consul-sync/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./k8s-gateway/ks.yaml
